apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-progressive-delivery
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/noxxspring/devops-progressive-delivery.git'
    targetRevision: HEAD
    path: manifests/argo-rollouts
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: online-boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
